/**
 * ESI Meta Spec
 * ESI specs and miscellaneous routes
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Per route status
 */
export interface GetStatusItem { 
    /**
     * ESI Endpoint cluster advertising this route
     */
    endpoint: string;
    /**
     * Swagger defined method
     */
    method: string;
    /**
     * Swagger defined route, not including version prefix
     */
    route: string;
    /**
     * Vague route status. Green is good, yellow is degraded, meaning slow or potentially dropping requests. Red means most requests are not succeeding and/or are very slow (5s+) on average.
     */
    status: GetStatusItem.StatusEnum;
    /**
     * Swagger tags applicable to this route
     */
    tags: Array<string>;
}
export namespace GetStatusItem {
    export type StatusEnum = 'green' | 'yellow' | 'red';
    export const StatusEnum = {
        Green: 'green' as StatusEnum,
        Yellow: 'yellow' as StatusEnum,
        Red: 'red' as StatusEnum
    };
}
