/**
 * ESI Meta Spec
 * ESI specs and miscellaneous routes
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * SSO /verify JSON
 */
export interface GetVerifyOk { 
    /**
     * Token owner's character ID
     */
    CharacterID: number;
    /**
     * Token owner's character name
     */
    CharacterName?: string;
    /**
     * Hash of the character's owner. If the character is sold or otherwise transferred, this will change
     */
    CharacterOwnerHash?: string;
    /**
     * Expiry time of the token (not RFC3339)
     */
    ExpiresOn?: string;
    /**
     * The IP which generated the token
     */
    IntellectualProperty?: string;
    /**
     * Space separated list of scopes the token is valid for
     */
    Scopes?: string;
    /**
     * Type of access token
     */
    TokenType?: string;
}
